FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Web API

Tesing **Get** request in Apiary Mock Server,

The header type for this request is **application/json**

The expacted status code is **200**



## test v1 [/v1/users]
Multiple objects with multiple properties **name**, **id**, **address** for a sample **GET** request 

### user [GET]

+ Response 200 (application/json)
        
        {
         "name": "John William",
        "id": "2584697",
        "email": "Jhon.William@yahoo.com",
        "address": "25941 wipping shadow ct, Arlington, VA 20598"
        }